server:
  port: 9000

logging:
  level:
    es:
      nom:
        marcosfernandez: DEBUG
    io:
      netty: DEBUG
      reactor: DEBUG

# MONGODB (MongoProperties)
spring:
  data:
    mongodb:
      uri: mongodb://superuser:jafSH8V5EetNYSfU@cluster0-shard-00-00-oucsw.mongodb.net:27017,cluster0-shard-00-01-oucsw.mongodb.net:27017,cluster0-shard-00-02-oucsw.mongodb.net:27017/admin?replicaSet=Cluster0-shard-0&ssl=true
      database: shares

# EMBEDDED MONGODB (EmbeddedMongoProperties)
# spring.mongodb.embedded.features=sync_delay # Comma-separated list of features to enable.
# spring.mongodb.embedded.storage.database-dir= # Directory used for data storage.
# spring.mongodb.embedded.storage.oplog-size= # Maximum size of the oplog, in megabytes.
# spring.mongodb.embedded.storage.repl-set-name= # Name of the replica set.
# spring.mongodb.embedded.version=3.2.2 # Version of Mongo to use.

# ACTUATOR Review
endpoints:
  autoconfig:
    enabled: true
  beans:
    enabled: true
  configprops:
    enabled: true
  dump:
    enabled: true
  env:
    enabled: true
  health:
    enabled: true
  info:
    enabled: true
  metrics:
    enabled: true
  mappings:
    enabled: true
  trace:
    enabled: true
